//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormReview
{
    public partial class AdminProducts
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtName;
        protected global::System.Web.UI.WebControls.TextBox txtPrice;
        protected global::System.Web.UI.WebControls.TextBox txtStock;
        protected global::System.Web.UI.WebControls.TextBox txtExpiryDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlPrescription;
        protected global::System.Web.UI.WebControls.Button btnAddProduct;
        protected global::System.Web.UI.WebControls.GridView gvAdmin;
    }
}
