<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AdminProducts.aspx.cs" Inherits="WebFormReview.AdminProducts" MasterPageFile="~/Master.Master" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        .admin-page {
            padding: 20px;
            width: 100%;
        }

        .page-title {
            color: #333;
            margin-bottom: 30px;
            font-size: 28px;
            font-weight: 700;
            text-align: center;
        }

        .add-product-form {
            background: white;
            padding: 25px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            margin-bottom: 30px;
            max-width: 600px;
            margin-left: auto;
            margin-right: auto;
        }

        .add-product-form h3 {
            color: #007bff;
            margin-bottom: 20px;
            text-align: center;
        }

        .form-row {
            margin-bottom: 15px;
        }

        .form-row label {
            display: block;
            margin-bottom: 5px;
            font-weight: 600;
            color: #333;
        }

        .form-row input, .form-row select {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
            box-sizing: border-box;
        }

        .btn-add {
            background: #28a745;
            color: white;
            padding: 12px 30px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-weight: bold;
            width: 100%;
            font-size: 16px;
        }

        .btn-add:hover {
            background: #218838;
        }

        .admin-grid {
            width: 100%;
            border-collapse: collapse;
            background-color: white;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        .admin-grid th {
            background: linear-gradient(135deg, #007bff 0%, #0056b3 100%);
            color: white;
            padding: 15px;
            text-align: left;
            font-weight: 600;
        }

        .admin-grid td {
            padding: 12px 15px;
            border: 1px solid #ddd;
        }

        .admin-grid tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .admin-grid tbody tr:hover {
            background-color: #f0f0f0;
        }

        .admin-grid input[type="text"] {
            padding: 6px;
            border: 1px solid #ddd;
            border-radius: 4px;
            width: 100%;
        }
    </style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="admin-page">
        <h1 class="page-title">🔧 Admin - Manage Products</h1>

        <div class="add-product-form">
            <h3>Add New Product</h3>
            <div class="form-row">
                <label>Product Name</label>
                <asp:TextBox ID="txtName" runat="server" placeholder="Enter product name" />
            </div>
            <div class="form-row">
                <label>Price</label>
                <asp:TextBox ID="txtPrice" runat="server" placeholder="Enter price" />
            </div>
            <div class="form-row">
                <label>Stock</label>
                <asp:TextBox ID="txtStock" runat="server" placeholder="Enter stock quantity" />
            </div>
            <div class="form-row">
                <label>Expiry Date</label>
                <asp:TextBox ID="txtExpiryDate" runat="server" TextMode="Date" />
            </div>
            <div class="form-row">
                <label>Requires Prescription</label>
                <asp:DropDownList ID="ddlPrescription" runat="server">
                    <asp:ListItem Text="No" Value="0" />
                    <asp:ListItem Text="Yes" Value="1" />
                </asp:DropDownList>
            </div>
            <asp:Button ID="btnAddProduct" runat="server" Text="Add Product" CssClass="btn-add" OnClick="btnAddProduct_Click" />
        </div>

        <asp:GridView ID="gvAdmin" runat="server" AutoGenerateColumns="False" DataKeyNames="ProductID"
            AutoGenerateEditButton="True" AutoGenerateDeleteButton="True"
            OnRowEditing="gvAdmin_RowEditing"
            OnRowUpdating="gvAdmin_RowUpdating"
            OnRowDeleting="gvAdmin_RowDeleting"
            OnRowCancelingEdit="gvAdmin_RowCancelingEdit"
            CssClass="admin-grid">
            <Columns>
                <asp:BoundField DataField="ProductID" HeaderText="ID" ReadOnly="True" />
                <asp:BoundField DataField="Name" HeaderText="Name" />
                <asp:BoundField DataField="Price" HeaderText="Price" DataFormatString="{0:C}" />
                <asp:BoundField DataField="Stock" HeaderText="Stock" />
                <asp:BoundField DataField="ExpiryDate" HeaderText="Expiry Date" DataFormatString="{0:dd/MM/yyyy}" />
                <asp:CheckBoxField DataField="RequiresPrescription" HeaderText="Prescription" />
            </Columns>
            <EmptyDataTemplate>
                <div style="text-align:center; padding:20px; color:#666;">No products found. Add your first product above.</div>
            </EmptyDataTemplate>
        </asp:GridView>
    </div>
</asp:Content>
