//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormReview
{
    public partial class Checkout
    {
        protected global::System.Web.UI.WebControls.Panel pnlCheckout;
        protected global::System.Web.UI.WebControls.GridView gvOrderItems;
        protected global::System.Web.UI.WebControls.Label lblSubtotal;
        protected global::System.Web.UI.WebControls.Label lblTax;
        protected global::System.Web.UI.WebControls.Label lblGrandTotal;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.Button btnPlaceOrder;
        protected global::System.Web.UI.WebControls.Button btnBackToCart;
        protected global::System.Web.UI.WebControls.Panel pnlEmptyCart;
        protected global::System.Web.UI.WebControls.Button btnShop;
    }
}
