//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormReview
{
    public partial class Wishlist
    {
        protected global::System.Web.UI.WebControls.GridView gvWishlist;
    }
}
